# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0011_auto_20171120_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webmention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('p', 'pending'), ('v', 'valid'), ('i', 'invalid'), ('d', 'deleted')], default='p', max_length=1)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='entries.Entry')),
            ],
            options={
                'default_related_name': 'mentions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='webmention',
            unique_together=set([('source', 'target')]),
        ),
    ]
