# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=users.models.avatar_path),
        ),
    ]
