# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171023_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profiles',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
