# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171031_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
