# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_xmpp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('name',)},
        ),
    ]
