# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 05:14
from __future__ import unicode_literals

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180124_1311'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
