# Generated by Django 2.0.7 on 2018-07-11 03:07

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180711_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid_sha256',
            field=computed_property.fields.ComputedCharField(compute_from='calc_openid_sha256', default='', editable=False,
                                                             help_text="SHA-256 hash of the user's OpenID URL, used for Libravatar", max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
