image: python:3.6
variables:
  GIT_SUBMODULE_STRATEGY: normal

install:
  stage: build
  script:
    - pip install pipenv
    - pipenv install

pytest:
  stage: test
  script:
    - pipenv run pytest
