image: python:3.6
variables:
  GIT_SUBMODULE_STRATEGY: normal
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.pip-cache
  PIPENV_VENV_IN_PROJECT: yeppers

cache:
  paths:
    - .pip-cache
    - .venv

test:
  script:
    - pip install pipenv
    - pipenv install
    - pipenv run pytest
