image: python:3.6
variables:
  GIT_SUBMODULE_STRATEGY: normal
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  PIPENV_CACHE_DIR: $CI_PROJECT_DIR/.cache/pipenv

cache:
  paths:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR

test:
  script:
    - pip install pipenv
    - pipenv sync --dev
    - pipenv run pytest
