image: python:3.6
variables:
  GIT_SUBMODULE_STRATEGY: normal

cache:
  paths:
    - ~/.cache/pip
    - ~/.local/share/virtualenvs

test:
  script:
    - pip install pipenv
    - pipenv install
    - pipenv run pytest
