language: python
cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
python:
  - '3.6'
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run pytest
