# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20171027_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='kind',
            field=models.CharField(choices=[('note', 'note'), ('article', 'article'), ('photo', 'photo')], db_index=True, default='note', max_length=30),
        ),
    ]
