# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20171113_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='cite',
            new_name='in_reply_to',
        ),
        migrations.AddField(
            model_name='entry',
            name='like_of',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='repost_of',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
