# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(related_name='entries', to='entries.Tag'),
        ),
    ]
