# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('entries', '0010_entry_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Cat',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='tags',
            new_name='cats',
        ),
    ]
