# Generated by Django 2.0.6 on 2018-06-28 10:44

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20171120_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syndication',
            options={'ordering': ['domain']},
        ),
        migrations.RemoveField(
            model_name='syndication',
            name='profile',
        ),
        migrations.AddField(
            model_name='syndication',
            name='domain',
            field=computed_property.fields.ComputedCharField(
                compute_from='calc_domain', default='', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
