# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 05:05
from __future__ import unicode_literals
from typing import List, Tuple

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]  # type: List[Tuple[str, str]]

    operations = [
        migrations.CreateModel(
            name='IndieAuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('me', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=255)),
                ('response_type', models.CharField(choices=[
                 ('id', 'id'), ('code', 'code')], default='id', max_length=4)),
                ('scope', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
